name: Gem release
on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d
        with:
          node-version: 20
      - uses: ruby/setup-ruby@250fcd6a742febb1123a77a841497ccaa8b9e939
        with:
          ruby-version: "3.2" # Not needed with a .ruby-version file

      - name: Install dependencies
        run: npm install && bundle install

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@61680d0e9b02ff86f5648ade99e01be17f0260a4
        env:
          GEM_HOST_API_KEY: ${{ secrets.GEM_HOST_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
